# RNN Intuition (From Scratch with NumPy)

Before diving into TensorFlow/Keras, let's understand exactly what a Recurrent Neural Network (RNN) does under the hood.

At its core, an RNN processes a sequence of words one by one. For every word, it calculates a **hidden state** (memory) using:
1. The current word's vector.
2. The previous word's hidden state.

### The Core Formula
`hidden_state = tanh( (W_x * x) + (W_h * previous_hidden) )`

- `x`: The current word vector.
- `previous_hidden`: What the network "remembers" so far.
- `W_x`: The weights applied to the new word.
- `W_h`: The weights applied to the past memory.
- `tanh`: An activation function that squashes numbers between -1 and 1 to keep them from exploding.

In [1]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Define our network dimensions
input_dim = 4    # Let's pretend our word embeddings are just length 4
hidden_dim = 3   # The size of the "memory" vector

# Initialize random weight matrices
# W_x transforms the input word (shape: input_dim -> hidden_dim)
W_x = np.random.randn(hidden_dim, input_dim)

# W_h transforms the previous memory (shape: hidden_dim -> hidden_dim)
W_h = np.random.randn(hidden_dim, hidden_dim)

print("W_x (Input Weights):\n", W_x)
print("\nW_h (Hidden Weights):\n", W_h)

W_x (Input Weights):
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]]

W_h (Hidden Weights):
 [[ 0.24196227 -1.91328024 -1.72491783]
 [-0.56228753 -1.01283112  0.31424733]
 [-0.90802408 -1.4123037   1.46564877]]


### Simulating a 3-Word Sentence
Let's say our sentence is: `["payment", "failed", "refund"]`

In [2]:
# Mock embeddings for our 3 words (length 4 each)
word_payment = np.array([0.9, 0.1, 0.0, 0.2])
word_failed  = np.array([0.0, 0.8, 0.5, 0.1])
word_refund  = np.array([0.1, 0.2, 0.9, 0.4])

sentence = [word_payment, word_failed, word_refund]
words = ["payment", "failed", "refund"]

# Initialize the first hidden state (Memory starts blank/at zero)
hidden_state = np.zeros(hidden_dim)
print(f"Initial memory state: {hidden_state}\n")

# Process the sentence word by word!
for i, x in enumerate(sentence):
    print(f"--- Processing Word {i+1}: '{words[i]}' ---")
    
    # 1. Look at the new word (W_x * x)
    input_contribution = np.dot(W_x, x)
    
    # 2. Look at the past memory (W_h * previous_hidden)
    memory_contribution = np.dot(W_h, hidden_state)
    
    # 3. Combine them and apply Tanh to get the new hidden state
    hidden_state = np.tanh(input_contribution + memory_contribution)
    
    print(f"Current Word Vector: {x}")
    print(f"New Hidden State: {hidden_state}\n")

print("=== Final Document Representation ===")
print("This final hidden state contains the 'memory' of all 3 words combined in order!")
print(hidden_state)

Initial memory state: [0. 0. 0.]

--- Processing Word 1: 'payment' ---
Current Word Vector: [0.9 0.1 0.  0.2]
New Hidden State: [ 0.62782763 -0.08049028 -0.43123831]

--- Processing Word 2: 'failed' ---
Current Word Vector: [0.  0.8 0.5 0.1]
New Hidden State: [ 0.88861381  0.26551111 -0.73184261]

--- Processing Word 3: 'refund' ---
Current Word Vector: [0.1 0.2 0.9 0.4]
New Hidden State: [ 0.9749411   0.57800975 -0.99257688]

=== Final Document Representation ===
This final hidden state contains the 'memory' of all 3 words combined in order!
[ 0.9749411   0.57800975 -0.99257688]
